keys:
  - &phoenix age1h59c0dlgye6ynxyee5rlj3shrug9n0x29p7zs5qvscsq40yaysvsqjv8vx

creation_rules:
  - path_regex: secrets/shared.yaml$
    key_groups:
      - age:
          - *phoenix

  - path_regex: secrets/phoenix.yaml$
    key_groups:
      - age:
          - *phoenix