{
  lib,
  pkgs,
  ...
}:
{
  programs.dconf.enable = true;
  home-manager.sharedModules = lib.singleton (
    { config, lib, ... }:
    {
      home.packages = with pkgs; [
        gnome-themes-extra
        papirus-icon-theme
        bibata-cursors
      ];

      home.sessionVariables = {
        CLUTTER_BACKEND = "wayland";
        SDL_VIDEODRIVER = "wayland";
        GSK_RENDERER = "gl";
        GDK_DPI_SCALE = "1";
        GDK_SCALE = "1";
        QT_AUTO_SCREEN_SCALE_FACTOR = "1";
        QT_QPA_PLATFORM = "wayland;xcb";
        QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
        QT_MEDIA_BACKEND = "ffmpeg";
        QT_FFMPEG_DECODING_HW_DEVICE_TYPES = "vaapi"; # Alternatives: drm, qsv, cuda,
        QT_FFMPEG_ENCODING_HW_DEVICE_TYPES = "vaapi"; # vdpau, opencl, vulkan
        ELECTRON_OZONE_PLATFORM_HINT = "auto";
      };
      # GTK apps are themed dynamically and qt apps follows it
      qt = {
        enable = true;
        platformTheme.name = "gtk3";
      };

      programs.niri.settings.spawn-at-startup = lib.singleton (
        let
          dts = pkgs.writeShellApplication {
            name = "dynamic-theme-switcher";
            runtimeInputs = [
              (pkgs.python3.withPackages (
                ps: with ps; [
                  pydbus
                  pygobject3
                ]
              ))
            ];
            text = ''
              export XDG_DATA_DIRS="${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}:${pkgs.gtk4}/share/gsettings-schemas/${pkgs.gtk4.name}:$XDG_DATA_DIRS"
              export GIO_EXTRA_MODULES="${pkgs.dconf.lib}/lib/gio/modules:${pkgs.gvfs}/lib/gio/modules"

              while true; do
                echo "[dynamic-theme-switcher]: starting..."
                python3 ${./dynamic-theme-switcher.py} || true
                echo "[dynamic-theme-switcher]: restarting in 2s..."
                sleep 2
              done
            '';
          };
        in
        {
          sh = "${lib.getExe dts} 2>&1 | logger -t dynamic-theme-switcher";
        }
      );

      systemd.user.services.apply-dms-theme-firefox = {
        Unit = {
          Description = "Apply custom themes generated by DMS to fiefox";
          After = [ "graphical-session.target" ];
          Wants = [ "graphical-session.target" ];
        };
        Service = {
          Type = "oneshot";
          ExecStart = pkgs.writeShellScript "apply-dms-theme-firefox" ''
            SRC="${config.xdg.configHome}/DankMaterialShell/firefox.css"
            DST="${config.home.homeDirectory}/.mozilla/firefox/dev/chrome/theme-material-blue.css"
            timeout=60
            while [ ! -e "$SRC" ] && [ $timeout -gt 0 ]; do
              sleep 1
              timeout=$((timeout - 1))
            done
            if [ ! -e "$SRC" ]; then
              echo "timed out waiting for $SRC" >&2
              exit 1
            fi
            mkdir -p "$(dirname "$DST")"
            rm -f "$DST"
            ln -sf "$SRC" "$DST"
          '';
          RemainAfterExit = false;
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
    }
  );
}
