{
  lib,
  pkgs,
  ...
}:
{
  config = lib.mkMerge [
    # xdg configuration
    {
      xdg = {
        autostart.enable = true;
        icons.enable = true;
        menus.enable = true;
        mime.enable = true;
        sounds.enable = true;
        portal = {
          enable = true;
          extraPortals = with pkgs; [
            xdg-desktop-portal-gtk
            xdg-desktop-portal-gnome
          ];
          config = {
            common.default = [
              "gtk"
              "gnome"
            ];
            niri = {
              default = [
                "gtk"
                "gnome"
              ];
              "org.freedesktop.impl.portal.ScreenCast" = [ "gnome" ];
              "org.freedesktop.impl.portal.FileChooser" = [ "gtk" ];
            };
          };
        };
      };
      home-manager.sharedModules = lib.singleton {
        xdg = {
          enable = true;
          autostart.enable = true;
          mime.enable = true;
          mimeApps.enable = true;
          portal = {
            enable = true;
            extraPortals = with pkgs; [
              xdg-desktop-portal-gtk
              xdg-desktop-portal-gnome
            ];
            config = {
              common.default = [
                "gtk"
                "gnome"
              ];
              niri = {
                default = [
                  "gtk"
                  "gnome"
                ];
                "org.freedesktop.impl.portal.ScreenCast" = [ "gnome" ];
                "org.freedesktop.impl.portal.FileChooser" = [ "gtk" ];
              };
            };
          };
          userDirs = {
            enable = true;
            desktop = null;
            templates = null;
            createDirectories = true;
          };
        };
      };
    }
    # Terminal
    {
      home-manager.sharedModules = lib.singleton {
        programs.ghostty = {
          enable = true;
          settings.theme = "dankcolors";
        };
        home.sessionVariables.TERMINAL = "ghostty";
        xdg.mimeApps.defaultApplications = {
          "x-scheme-handler/terminal" = "com.mitchellh.ghostty.desktop";
        };
        # Hack bcoz the file may not exist at activation time, its generated by DMS
        xdg.configFile."ghostty/config".onChange = "";
      };
    }
    # File manager
    {
      environment.systemPackages = with pkgs; [
        nautilus
        file-roller
      ];
      services.gvfs.enable = true;
      programs.nautilus-open-any-terminal = {
        enable = true;
        terminal = "ghostty";
      };
      home-manager.sharedModules = lib.singleton {
        xdg.mimeApps.defaultApplications = {
          "inode/directory" = lib.mkBefore [ "org.gnome.Nautilus.desktop" ];
        };
      };
      nixdesk.core.storage.systemDisk.impermanence.user.dirs = [
        "@dataHome/gvfs-metadata"
      ];
    }
  ];
}
